'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34014
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34014.
'
Namespace ComunicacionDataTrack
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="VideoDataSoap", [Namespace]:="http://190.24.175.109:2998/")>  _
    Partial Public Class VideoData
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetLastPositionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetLastPositionWithOdometerOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetLastPositionIDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetLastVehicleDataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SetVehicleSellDataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetVideoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private retrieveEventStringV3OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ComunicadorDataTrack.My.MySettings.Default.ComunicadorDataTrack_ComunicacionDataTrack_VideoData
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetLastPositionCompleted As GetLastPositionCompletedEventHandler
        
        '''<remarks/>
        Public Event GetLastPositionWithOdometerCompleted As GetLastPositionWithOdometerCompletedEventHandler
        
        '''<remarks/>
        Public Event GetLastPositionIDCompleted As GetLastPositionIDCompletedEventHandler
        
        '''<remarks/>
        Public Event GetLastVehicleDataCompleted As GetLastVehicleDataCompletedEventHandler
        
        '''<remarks/>
        Public Event SetVehicleSellDataCompleted As SetVehicleSellDataCompletedEventHandler
        
        '''<remarks/>
        Public Event GetVideoCompleted As GetVideoCompletedEventHandler
        
        '''<remarks/>
        Public Event retrieveEventStringV3Completed As retrieveEventStringV3CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.24.175.109:2998/GetLastPosition", RequestNamespace:="http://190.24.175.109:2998/", ResponseNamespace:="http://190.24.175.109:2998/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetLastPosition(ByVal sUser As String, ByVal sPassw As String, ByVal sPlate As String) As String
            Dim results() As Object = Me.Invoke("GetLastPosition", New Object() {sUser, sPassw, sPlate})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetLastPositionAsync(ByVal sUser As String, ByVal sPassw As String, ByVal sPlate As String)
            Me.GetLastPositionAsync(sUser, sPassw, sPlate, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetLastPositionAsync(ByVal sUser As String, ByVal sPassw As String, ByVal sPlate As String, ByVal userState As Object)
            If (Me.GetLastPositionOperationCompleted Is Nothing) Then
                Me.GetLastPositionOperationCompleted = AddressOf Me.OnGetLastPositionOperationCompleted
            End If
            Me.InvokeAsync("GetLastPosition", New Object() {sUser, sPassw, sPlate}, Me.GetLastPositionOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetLastPositionOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetLastPositionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetLastPositionCompleted(Me, New GetLastPositionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.24.175.109:2998/GetLastPositionWithOdometer", RequestNamespace:="http://190.24.175.109:2998/", ResponseNamespace:="http://190.24.175.109:2998/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetLastPositionWithOdometer(ByVal sUser As String, ByVal sPassw As String, ByVal sPlate As String) As String
            Dim results() As Object = Me.Invoke("GetLastPositionWithOdometer", New Object() {sUser, sPassw, sPlate})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetLastPositionWithOdometerAsync(ByVal sUser As String, ByVal sPassw As String, ByVal sPlate As String)
            Me.GetLastPositionWithOdometerAsync(sUser, sPassw, sPlate, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetLastPositionWithOdometerAsync(ByVal sUser As String, ByVal sPassw As String, ByVal sPlate As String, ByVal userState As Object)
            If (Me.GetLastPositionWithOdometerOperationCompleted Is Nothing) Then
                Me.GetLastPositionWithOdometerOperationCompleted = AddressOf Me.OnGetLastPositionWithOdometerOperationCompleted
            End If
            Me.InvokeAsync("GetLastPositionWithOdometer", New Object() {sUser, sPassw, sPlate}, Me.GetLastPositionWithOdometerOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetLastPositionWithOdometerOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetLastPositionWithOdometerCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetLastPositionWithOdometerCompleted(Me, New GetLastPositionWithOdometerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.24.175.109:2998/GetLastPositionID", RequestNamespace:="http://190.24.175.109:2998/", ResponseNamespace:="http://190.24.175.109:2998/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetLastPositionID(ByVal sUser As String, ByVal sPassw As String, ByVal sID As String) As String
            Dim results() As Object = Me.Invoke("GetLastPositionID", New Object() {sUser, sPassw, sID})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetLastPositionIDAsync(ByVal sUser As String, ByVal sPassw As String, ByVal sID As String)
            Me.GetLastPositionIDAsync(sUser, sPassw, sID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetLastPositionIDAsync(ByVal sUser As String, ByVal sPassw As String, ByVal sID As String, ByVal userState As Object)
            If (Me.GetLastPositionIDOperationCompleted Is Nothing) Then
                Me.GetLastPositionIDOperationCompleted = AddressOf Me.OnGetLastPositionIDOperationCompleted
            End If
            Me.InvokeAsync("GetLastPositionID", New Object() {sUser, sPassw, sID}, Me.GetLastPositionIDOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetLastPositionIDOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetLastPositionIDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetLastPositionIDCompleted(Me, New GetLastPositionIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.24.175.109:2998/GetLastVehicleData", RequestNamespace:="http://190.24.175.109:2998/", ResponseNamespace:="http://190.24.175.109:2998/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetLastVehicleData(ByVal sUser As String, ByVal sPassw As String, ByVal sPlate As String) As String
            Dim results() As Object = Me.Invoke("GetLastVehicleData", New Object() {sUser, sPassw, sPlate})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetLastVehicleDataAsync(ByVal sUser As String, ByVal sPassw As String, ByVal sPlate As String)
            Me.GetLastVehicleDataAsync(sUser, sPassw, sPlate, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetLastVehicleDataAsync(ByVal sUser As String, ByVal sPassw As String, ByVal sPlate As String, ByVal userState As Object)
            If (Me.GetLastVehicleDataOperationCompleted Is Nothing) Then
                Me.GetLastVehicleDataOperationCompleted = AddressOf Me.OnGetLastVehicleDataOperationCompleted
            End If
            Me.InvokeAsync("GetLastVehicleData", New Object() {sUser, sPassw, sPlate}, Me.GetLastVehicleDataOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetLastVehicleDataOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetLastVehicleDataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetLastVehicleDataCompleted(Me, New GetLastVehicleDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.24.175.109:2998/SetVehicleSellData", RequestNamespace:="http://190.24.175.109:2998/", ResponseNamespace:="http://190.24.175.109:2998/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SetVehicleSellData(ByVal sUser As String, ByVal sPassw As String, ByVal DatosVenta As String) As String
            Dim results() As Object = Me.Invoke("SetVehicleSellData", New Object() {sUser, sPassw, DatosVenta})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SetVehicleSellDataAsync(ByVal sUser As String, ByVal sPassw As String, ByVal DatosVenta As String)
            Me.SetVehicleSellDataAsync(sUser, sPassw, DatosVenta, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetVehicleSellDataAsync(ByVal sUser As String, ByVal sPassw As String, ByVal DatosVenta As String, ByVal userState As Object)
            If (Me.SetVehicleSellDataOperationCompleted Is Nothing) Then
                Me.SetVehicleSellDataOperationCompleted = AddressOf Me.OnSetVehicleSellDataOperationCompleted
            End If
            Me.InvokeAsync("SetVehicleSellData", New Object() {sUser, sPassw, DatosVenta}, Me.SetVehicleSellDataOperationCompleted, userState)
        End Sub
        
        Private Sub OnSetVehicleSellDataOperationCompleted(ByVal arg As Object)
            If (Not (Me.SetVehicleSellDataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SetVehicleSellDataCompleted(Me, New SetVehicleSellDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.24.175.109:2998/GetVideo", RequestNamespace:="http://190.24.175.109:2998/", ResponseNamespace:="http://190.24.175.109:2998/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetVideo(ByVal sIdVehiculo As String, ByVal sCamara As String, ByVal sFechaInicial As String, ByVal sFechaFinal As String, ByVal sPassword As String) As String
            Dim results() As Object = Me.Invoke("GetVideo", New Object() {sIdVehiculo, sCamara, sFechaInicial, sFechaFinal, sPassword})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetVideoAsync(ByVal sIdVehiculo As String, ByVal sCamara As String, ByVal sFechaInicial As String, ByVal sFechaFinal As String, ByVal sPassword As String)
            Me.GetVideoAsync(sIdVehiculo, sCamara, sFechaInicial, sFechaFinal, sPassword, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetVideoAsync(ByVal sIdVehiculo As String, ByVal sCamara As String, ByVal sFechaInicial As String, ByVal sFechaFinal As String, ByVal sPassword As String, ByVal userState As Object)
            If (Me.GetVideoOperationCompleted Is Nothing) Then
                Me.GetVideoOperationCompleted = AddressOf Me.OnGetVideoOperationCompleted
            End If
            Me.InvokeAsync("GetVideo", New Object() {sIdVehiculo, sCamara, sFechaInicial, sFechaFinal, sPassword}, Me.GetVideoOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetVideoOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetVideoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetVideoCompleted(Me, New GetVideoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.24.175.109:2998/retrieveEventStringV3", RequestNamespace:="http://190.24.175.109:2998/", ResponseNamespace:="http://190.24.175.109:2998/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function retrieveEventStringV3(ByVal sUser As String, ByVal sClave As String, ByVal sPlaca As String, ByVal sEvento As String, ByVal sFHInicial As String, ByVal sFHFinal As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("retrieveEventStringV3", New Object() {sUser, sClave, sPlaca, sEvento, sFHInicial, sFHFinal})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub retrieveEventStringV3Async(ByVal sUser As String, ByVal sClave As String, ByVal sPlaca As String, ByVal sEvento As String, ByVal sFHInicial As String, ByVal sFHFinal As String)
            Me.retrieveEventStringV3Async(sUser, sClave, sPlaca, sEvento, sFHInicial, sFHFinal, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub retrieveEventStringV3Async(ByVal sUser As String, ByVal sClave As String, ByVal sPlaca As String, ByVal sEvento As String, ByVal sFHInicial As String, ByVal sFHFinal As String, ByVal userState As Object)
            If (Me.retrieveEventStringV3OperationCompleted Is Nothing) Then
                Me.retrieveEventStringV3OperationCompleted = AddressOf Me.OnretrieveEventStringV3OperationCompleted
            End If
            Me.InvokeAsync("retrieveEventStringV3", New Object() {sUser, sClave, sPlaca, sEvento, sFHInicial, sFHFinal}, Me.retrieveEventStringV3OperationCompleted, userState)
        End Sub
        
        Private Sub OnretrieveEventStringV3OperationCompleted(ByVal arg As Object)
            If (Not (Me.retrieveEventStringV3CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent retrieveEventStringV3Completed(Me, New retrieveEventStringV3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub GetLastPositionCompletedEventHandler(ByVal sender As Object, ByVal e As GetLastPositionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetLastPositionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub GetLastPositionWithOdometerCompletedEventHandler(ByVal sender As Object, ByVal e As GetLastPositionWithOdometerCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetLastPositionWithOdometerCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub GetLastPositionIDCompletedEventHandler(ByVal sender As Object, ByVal e As GetLastPositionIDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetLastPositionIDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub GetLastVehicleDataCompletedEventHandler(ByVal sender As Object, ByVal e As GetLastVehicleDataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetLastVehicleDataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub SetVehicleSellDataCompletedEventHandler(ByVal sender As Object, ByVal e As SetVehicleSellDataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SetVehicleSellDataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub GetVideoCompletedEventHandler(ByVal sender As Object, ByVal e As GetVideoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetVideoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub retrieveEventStringV3CompletedEventHandler(ByVal sender As Object, ByVal e As retrieveEventStringV3CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class retrieveEventStringV3CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
End Namespace
