'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34014
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34014.
'
Namespace ServicioMeno_Cash
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="IntegracionServiceCorePortBinding", [Namespace]:="http://ws.sexternos.iev.ptesa.com/")>  _
    Partial Public Class IntegracionServiceCore
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private PreautorizarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConfirmarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.POSstation.ServerServices.My.MySettings.Default.ServerServices_ServicioMenoCash1_CentroInformacion
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event PreautorizarCompleted As PreautorizarCompletedEventHandler
        
        '''<remarks/>
        Public Event ConfirmarCompleted As ConfirmarCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://ws.sexternos.iev.ptesa.com/", ResponseNamespace:="http://ws.sexternos.iev.ptesa.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Preautorizar(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal dto As preautorizacionDTO) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> respuestaPreDTO
            Dim results() As Object = Me.Invoke("Preautorizar", New Object() {dto})
            Return CType(results(0),respuestaPreDTO)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PreautorizarAsync(ByVal dto As preautorizacionDTO)
            Me.PreautorizarAsync(dto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PreautorizarAsync(ByVal dto As preautorizacionDTO, ByVal userState As Object)
            If (Me.PreautorizarOperationCompleted Is Nothing) Then
                Me.PreautorizarOperationCompleted = AddressOf Me.OnPreautorizarOperationCompleted
            End If
            Me.InvokeAsync("Preautorizar", New Object() {dto}, Me.PreautorizarOperationCompleted, userState)
        End Sub
        
        Private Sub OnPreautorizarOperationCompleted(ByVal arg As Object)
            If (Not (Me.PreautorizarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PreautorizarCompleted(Me, New PreautorizarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://ws.sexternos.iev.ptesa.com/", ResponseNamespace:="http://ws.sexternos.iev.ptesa.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Confirmar(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal dto As confirmacionDTO) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> respuestaConfDTO
            Dim results() As Object = Me.Invoke("Confirmar", New Object() {dto})
            Return CType(results(0),respuestaConfDTO)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConfirmarAsync(ByVal dto As confirmacionDTO)
            Me.ConfirmarAsync(dto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConfirmarAsync(ByVal dto As confirmacionDTO, ByVal userState As Object)
            If (Me.ConfirmarOperationCompleted Is Nothing) Then
                Me.ConfirmarOperationCompleted = AddressOf Me.OnConfirmarOperationCompleted
            End If
            Me.InvokeAsync("Confirmar", New Object() {dto}, Me.ConfirmarOperationCompleted, userState)
        End Sub
        
        Private Sub OnConfirmarOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConfirmarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConfirmarCompleted(Me, New ConfirmarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.sexternos.iev.ptesa.com/")>  _
    Partial Public Class preautorizacionDTO
        
        Private caraField As Integer
        
        Private caraFieldSpecified As Boolean
        
        Private codigoEstacionField As String
        
        Private direccionIPField As String
        
        Private islaField As Integer
        
        Private islaFieldSpecified As Boolean
        
        Private kilometrosField As Long
        
        Private kilometrosFieldSpecified As Boolean
        
        Private mangueraField As Integer
        
        Private mangueraFieldSpecified As Boolean
        
        Private numAuditoriaField As String
        
        Private precioField As Double
        
        Private precioFieldSpecified As Boolean
        
        Private productoField As Integer
        
        Private productoFieldSpecified As Boolean
        
        Private rOMField As String
        
        Private surtidorField As Integer
        
        Private surtidorFieldSpecified As Boolean
        
        Private unidadMedidaField As Integer
        
        Private unidadMedidaFieldSpecified As Boolean
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property cara() As Integer
            Get
                Return Me.caraField
            End Get
            Set
                Me.caraField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property caraSpecified() As Boolean
            Get
                Return Me.caraFieldSpecified
            End Get
            Set
                Me.caraFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigoEstacion() As String
            Get
                Return Me.codigoEstacionField
            End Get
            Set
                Me.codigoEstacionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property direccionIP() As String
            Get
                Return Me.direccionIPField
            End Get
            Set
                Me.direccionIPField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property isla() As Integer
            Get
                Return Me.islaField
            End Get
            Set
                Me.islaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property islaSpecified() As Boolean
            Get
                Return Me.islaFieldSpecified
            End Get
            Set
                Me.islaFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property kilometros() As Long
            Get
                Return Me.kilometrosField
            End Get
            Set
                Me.kilometrosField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property kilometrosSpecified() As Boolean
            Get
                Return Me.kilometrosFieldSpecified
            End Get
            Set
                Me.kilometrosFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property manguera() As Integer
            Get
                Return Me.mangueraField
            End Get
            Set
                Me.mangueraField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property mangueraSpecified() As Boolean
            Get
                Return Me.mangueraFieldSpecified
            End Get
            Set
                Me.mangueraFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numAuditoria() As String
            Get
                Return Me.numAuditoriaField
            End Get
            Set
                Me.numAuditoriaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property precio() As Double
            Get
                Return Me.precioField
            End Get
            Set
                Me.precioField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property precioSpecified() As Boolean
            Get
                Return Me.precioFieldSpecified
            End Get
            Set
                Me.precioFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property producto() As Integer
            Get
                Return Me.productoField
            End Get
            Set
                Me.productoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property productoSpecified() As Boolean
            Get
                Return Me.productoFieldSpecified
            End Get
            Set
                Me.productoFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ROM() As String
            Get
                Return Me.rOMField
            End Get
            Set
                Me.rOMField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property surtidor() As Integer
            Get
                Return Me.surtidorField
            End Get
            Set
                Me.surtidorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property surtidorSpecified() As Boolean
            Get
                Return Me.surtidorFieldSpecified
            End Get
            Set
                Me.surtidorFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property unidadMedida() As Integer
            Get
                Return Me.unidadMedidaField
            End Get
            Set
                Me.unidadMedidaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property unidadMedidaSpecified() As Boolean
            Get
                Return Me.unidadMedidaFieldSpecified
            End Get
            Set
                Me.unidadMedidaFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.sexternos.iev.ptesa.com/")>  _
    Partial Public Class respuestaConfDTO
        
        Private codigoField As String
        
        Private fechaField As Date
        
        Private fechaFieldSpecified As Boolean
        
        Private mensajeField As String
        
        Private nombreField As String
        
        Private numeroField As String
        
        Private placaField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaSpecified() As Boolean
            Get
                Return Me.fechaFieldSpecified
            End Get
            Set
                Me.fechaFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numero() As String
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property placa() As String
            Get
                Return Me.placaField
            End Get
            Set
                Me.placaField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.sexternos.iev.ptesa.com/")>  _
    Partial Public Class confirmacionDTO
        
        Private cantidadField As Double
        
        Private cantidadFieldSpecified As Boolean
        
        Private direccionIPField As String
        
        Private fechaField As Date
        
        Private fechaFieldSpecified As Boolean
        
        Private kilometrosField As Integer
        
        Private kilometrosFieldSpecified As Boolean
        
        Private numeroField As String
        
        Private precioUnidadField As Decimal
        
        Private precioUnidadFieldSpecified As Boolean
        
        Private productoField As Integer
        
        Private productoFieldSpecified As Boolean
        
        Private unidadMedidaField As Integer
        
        Private unidadMedidaFieldSpecified As Boolean
        
        Private valorField As Double
        
        Private valorFieldSpecified As Boolean
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property cantidad() As Double
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property cantidadSpecified() As Boolean
            Get
                Return Me.cantidadFieldSpecified
            End Get
            Set
                Me.cantidadFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property direccionIP() As String
            Get
                Return Me.direccionIPField
            End Get
            Set
                Me.direccionIPField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaSpecified() As Boolean
            Get
                Return Me.fechaFieldSpecified
            End Get
            Set
                Me.fechaFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property kilometros() As Integer
            Get
                Return Me.kilometrosField
            End Get
            Set
                Me.kilometrosField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property kilometrosSpecified() As Boolean
            Get
                Return Me.kilometrosFieldSpecified
            End Get
            Set
                Me.kilometrosFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numero() As String
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property precioUnidad() As Decimal
            Get
                Return Me.precioUnidadField
            End Get
            Set
                Me.precioUnidadField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property precioUnidadSpecified() As Boolean
            Get
                Return Me.precioUnidadFieldSpecified
            End Get
            Set
                Me.precioUnidadFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property producto() As Integer
            Get
                Return Me.productoField
            End Get
            Set
                Me.productoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property productoSpecified() As Boolean
            Get
                Return Me.productoFieldSpecified
            End Get
            Set
                Me.productoFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property unidadMedida() As Integer
            Get
                Return Me.unidadMedidaField
            End Get
            Set
                Me.unidadMedidaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property unidadMedidaSpecified() As Boolean
            Get
                Return Me.unidadMedidaFieldSpecified
            End Get
            Set
                Me.unidadMedidaFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property valor() As Double
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property valorSpecified() As Boolean
            Get
                Return Me.valorFieldSpecified
            End Get
            Set
                Me.valorFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.sexternos.iev.ptesa.com/")>  _
    Partial Public Class respuestaPreDTO
        
        Private codigoField As String
        
        Private fechaField As Date
        
        Private fechaFieldSpecified As Boolean
        
        Private mensajeField As String
        
        Private numeroField As String
        
        Private valorField As Double
        
        Private valorFieldSpecified As Boolean
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaSpecified() As Boolean
            Get
                Return Me.fechaFieldSpecified
            End Get
            Set
                Me.fechaFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numero() As String
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property valor() As Double
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property valorSpecified() As Boolean
            Get
                Return Me.valorFieldSpecified
            End Get
            Set
                Me.valorFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub PreautorizarCompletedEventHandler(ByVal sender As Object, ByVal e As PreautorizarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PreautorizarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As respuestaPreDTO
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),respuestaPreDTO)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub ConfirmarCompletedEventHandler(ByVal sender As Object, ByVal e As ConfirmarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConfirmarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As respuestaConfDTO
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),respuestaConfDTO)
            End Get
        End Property
    End Class
End Namespace
