'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18052
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18052.
'
Namespace Fidelizacion
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="FidelizacionSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Fidelizacion
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private RegistrarVentaFidelizadaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegistrarVentaFidelizadaPorNroConductorOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarSaldosTarjetaPorEDSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarInformacionPremioBonoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarSaldosTarjetaConIdentificacionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AutorizarRedencionPremioBonoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AutorizarRedencionBonosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AutorizarRedencionBonosConIdentificacionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConfirmacionRedencionBonosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CancelarRedencionBonosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.gasolutions.Fidelizador.My.MySettings.Default.Fidelizador_Fidelizacion_Fidelizacion
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event RegistrarVentaFidelizadaCompleted As RegistrarVentaFidelizadaCompletedEventHandler
        
        '''<remarks/>
        Public Event RegistrarVentaFidelizadaPorNroConductorCompleted As RegistrarVentaFidelizadaPorNroConductorCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarSaldosTarjetaPorEDSCompleted As ConsultarSaldosTarjetaPorEDSCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarInformacionPremioBonoCompleted As ConsultarInformacionPremioBonoCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarSaldosTarjetaConIdentificacionCompleted As ConsultarSaldosTarjetaConIdentificacionCompletedEventHandler
        
        '''<remarks/>
        Public Event AutorizarRedencionPremioBonoCompleted As AutorizarRedencionPremioBonoCompletedEventHandler
        
        '''<remarks/>
        Public Event AutorizarRedencionBonosCompleted As AutorizarRedencionBonosCompletedEventHandler
        
        '''<remarks/>
        Public Event AutorizarRedencionBonosConIdentificacionCompleted As AutorizarRedencionBonosConIdentificacionCompletedEventHandler
        
        '''<remarks/>
        Public Event ConfirmacionRedencionBonosCompleted As ConfirmacionRedencionBonosCompletedEventHandler
        
        '''<remarks/>
        Public Event CancelarRedencionBonosCompleted As CancelarRedencionBonosCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarVentaFidelizada", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegistrarVentaFidelizada(ByVal recibo As Long, ByVal fechahora As String, ByVal cantidad As Decimal, ByVal valor As Decimal, ByVal placa As String, ByVal idproducto As Integer, ByVal codEstacion As String, ByVal tarjeta As String) As String
            Dim results() As Object = Me.Invoke("RegistrarVentaFidelizada", New Object() {recibo, fechahora, cantidad, valor, placa, idproducto, codEstacion, tarjeta})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistrarVentaFidelizadaAsync(ByVal recibo As Long, ByVal fechahora As String, ByVal cantidad As Decimal, ByVal valor As Decimal, ByVal placa As String, ByVal idproducto As Integer, ByVal codEstacion As String, ByVal tarjeta As String)
            Me.RegistrarVentaFidelizadaAsync(recibo, fechahora, cantidad, valor, placa, idproducto, codEstacion, tarjeta, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistrarVentaFidelizadaAsync(ByVal recibo As Long, ByVal fechahora As String, ByVal cantidad As Decimal, ByVal valor As Decimal, ByVal placa As String, ByVal idproducto As Integer, ByVal codEstacion As String, ByVal tarjeta As String, ByVal userState As Object)
            If (Me.RegistrarVentaFidelizadaOperationCompleted Is Nothing) Then
                Me.RegistrarVentaFidelizadaOperationCompleted = AddressOf Me.OnRegistrarVentaFidelizadaOperationCompleted
            End If
            Me.InvokeAsync("RegistrarVentaFidelizada", New Object() {recibo, fechahora, cantidad, valor, placa, idproducto, codEstacion, tarjeta}, Me.RegistrarVentaFidelizadaOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistrarVentaFidelizadaOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegistrarVentaFidelizadaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistrarVentaFidelizadaCompleted(Me, New RegistrarVentaFidelizadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarVentaFidelizadaPorNroConductor", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegistrarVentaFidelizadaPorNroConductor(ByVal recibo As Long, ByVal fechahora As String, ByVal cantidad As Decimal, ByVal valor As Decimal, ByVal placa As String, ByVal idproducto As Integer, ByVal codEstacion As String, ByVal nroConductor As String) As String
            Dim results() As Object = Me.Invoke("RegistrarVentaFidelizadaPorNroConductor", New Object() {recibo, fechahora, cantidad, valor, placa, idproducto, codEstacion, nroConductor})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistrarVentaFidelizadaPorNroConductorAsync(ByVal recibo As Long, ByVal fechahora As String, ByVal cantidad As Decimal, ByVal valor As Decimal, ByVal placa As String, ByVal idproducto As Integer, ByVal codEstacion As String, ByVal nroConductor As String)
            Me.RegistrarVentaFidelizadaPorNroConductorAsync(recibo, fechahora, cantidad, valor, placa, idproducto, codEstacion, nroConductor, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistrarVentaFidelizadaPorNroConductorAsync(ByVal recibo As Long, ByVal fechahora As String, ByVal cantidad As Decimal, ByVal valor As Decimal, ByVal placa As String, ByVal idproducto As Integer, ByVal codEstacion As String, ByVal nroConductor As String, ByVal userState As Object)
            If (Me.RegistrarVentaFidelizadaPorNroConductorOperationCompleted Is Nothing) Then
                Me.RegistrarVentaFidelizadaPorNroConductorOperationCompleted = AddressOf Me.OnRegistrarVentaFidelizadaPorNroConductorOperationCompleted
            End If
            Me.InvokeAsync("RegistrarVentaFidelizadaPorNroConductor", New Object() {recibo, fechahora, cantidad, valor, placa, idproducto, codEstacion, nroConductor}, Me.RegistrarVentaFidelizadaPorNroConductorOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistrarVentaFidelizadaPorNroConductorOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegistrarVentaFidelizadaPorNroConductorCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistrarVentaFidelizadaPorNroConductorCompleted(Me, New RegistrarVentaFidelizadaPorNroConductorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarSaldosTarjetaPorEDS", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarSaldosTarjetaPorEDS(ByVal codEstacion As String, ByVal tarjeta As String) As RespuestaFidelizacion
            Dim results() As Object = Me.Invoke("ConsultarSaldosTarjetaPorEDS", New Object() {codEstacion, tarjeta})
            Return CType(results(0),RespuestaFidelizacion)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarSaldosTarjetaPorEDSAsync(ByVal codEstacion As String, ByVal tarjeta As String)
            Me.ConsultarSaldosTarjetaPorEDSAsync(codEstacion, tarjeta, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarSaldosTarjetaPorEDSAsync(ByVal codEstacion As String, ByVal tarjeta As String, ByVal userState As Object)
            If (Me.ConsultarSaldosTarjetaPorEDSOperationCompleted Is Nothing) Then
                Me.ConsultarSaldosTarjetaPorEDSOperationCompleted = AddressOf Me.OnConsultarSaldosTarjetaPorEDSOperationCompleted
            End If
            Me.InvokeAsync("ConsultarSaldosTarjetaPorEDS", New Object() {codEstacion, tarjeta}, Me.ConsultarSaldosTarjetaPorEDSOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarSaldosTarjetaPorEDSOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarSaldosTarjetaPorEDSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarSaldosTarjetaPorEDSCompleted(Me, New ConsultarSaldosTarjetaPorEDSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarInformacionPremioBono", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarInformacionPremioBono(ByVal codEstacion As String, ByVal numero As String, ByVal idtipoIdentificadorFidelizacion As TipoIdentificadorFidelizacion) As RespuestaInformacionPremio
            Dim results() As Object = Me.Invoke("ConsultarInformacionPremioBono", New Object() {codEstacion, numero, idtipoIdentificadorFidelizacion})
            Return CType(results(0),RespuestaInformacionPremio)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarInformacionPremioBonoAsync(ByVal codEstacion As String, ByVal numero As String, ByVal idtipoIdentificadorFidelizacion As TipoIdentificadorFidelizacion)
            Me.ConsultarInformacionPremioBonoAsync(codEstacion, numero, idtipoIdentificadorFidelizacion, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarInformacionPremioBonoAsync(ByVal codEstacion As String, ByVal numero As String, ByVal idtipoIdentificadorFidelizacion As TipoIdentificadorFidelizacion, ByVal userState As Object)
            If (Me.ConsultarInformacionPremioBonoOperationCompleted Is Nothing) Then
                Me.ConsultarInformacionPremioBonoOperationCompleted = AddressOf Me.OnConsultarInformacionPremioBonoOperationCompleted
            End If
            Me.InvokeAsync("ConsultarInformacionPremioBono", New Object() {codEstacion, numero, idtipoIdentificadorFidelizacion}, Me.ConsultarInformacionPremioBonoOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarInformacionPremioBonoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarInformacionPremioBonoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarInformacionPremioBonoCompleted(Me, New ConsultarInformacionPremioBonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarSaldosTarjetaConIdentificacion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarSaldosTarjetaConIdentificacion(ByVal codEstacion As String, ByVal rut As String) As RespuestaFidelizacion
            Dim results() As Object = Me.Invoke("ConsultarSaldosTarjetaConIdentificacion", New Object() {codEstacion, rut})
            Return CType(results(0),RespuestaFidelizacion)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarSaldosTarjetaConIdentificacionAsync(ByVal codEstacion As String, ByVal rut As String)
            Me.ConsultarSaldosTarjetaConIdentificacionAsync(codEstacion, rut, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarSaldosTarjetaConIdentificacionAsync(ByVal codEstacion As String, ByVal rut As String, ByVal userState As Object)
            If (Me.ConsultarSaldosTarjetaConIdentificacionOperationCompleted Is Nothing) Then
                Me.ConsultarSaldosTarjetaConIdentificacionOperationCompleted = AddressOf Me.OnConsultarSaldosTarjetaConIdentificacionOperationCompleted
            End If
            Me.InvokeAsync("ConsultarSaldosTarjetaConIdentificacion", New Object() {codEstacion, rut}, Me.ConsultarSaldosTarjetaConIdentificacionOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarSaldosTarjetaConIdentificacionOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarSaldosTarjetaConIdentificacionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarSaldosTarjetaConIdentificacionCompleted(Me, New ConsultarSaldosTarjetaConIdentificacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AutorizarRedencionPremioBono", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AutorizarRedencionPremioBono(ByVal codEstacion As String, ByVal numero As String, ByVal recibo As String, ByVal valor As Decimal, ByVal cantidad As Decimal, ByVal cantidadPremio As Decimal, ByVal idPremio As Integer, ByVal idTipoIdentificador As TipoIdentificadorFidelizacion) As RespuestaRedencionBono
            Dim results() As Object = Me.Invoke("AutorizarRedencionPremioBono", New Object() {codEstacion, numero, recibo, valor, cantidad, cantidadPremio, idPremio, idTipoIdentificador})
            Return CType(results(0),RespuestaRedencionBono)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AutorizarRedencionPremioBonoAsync(ByVal codEstacion As String, ByVal numero As String, ByVal recibo As String, ByVal valor As Decimal, ByVal cantidad As Decimal, ByVal cantidadPremio As Decimal, ByVal idPremio As Integer, ByVal idTipoIdentificador As TipoIdentificadorFidelizacion)
            Me.AutorizarRedencionPremioBonoAsync(codEstacion, numero, recibo, valor, cantidad, cantidadPremio, idPremio, idTipoIdentificador, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AutorizarRedencionPremioBonoAsync(ByVal codEstacion As String, ByVal numero As String, ByVal recibo As String, ByVal valor As Decimal, ByVal cantidad As Decimal, ByVal cantidadPremio As Decimal, ByVal idPremio As Integer, ByVal idTipoIdentificador As TipoIdentificadorFidelizacion, ByVal userState As Object)
            If (Me.AutorizarRedencionPremioBonoOperationCompleted Is Nothing) Then
                Me.AutorizarRedencionPremioBonoOperationCompleted = AddressOf Me.OnAutorizarRedencionPremioBonoOperationCompleted
            End If
            Me.InvokeAsync("AutorizarRedencionPremioBono", New Object() {codEstacion, numero, recibo, valor, cantidad, cantidadPremio, idPremio, idTipoIdentificador}, Me.AutorizarRedencionPremioBonoOperationCompleted, userState)
        End Sub
        
        Private Sub OnAutorizarRedencionPremioBonoOperationCompleted(ByVal arg As Object)
            If (Not (Me.AutorizarRedencionPremioBonoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AutorizarRedencionPremioBonoCompleted(Me, New AutorizarRedencionPremioBonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AutorizarRedencionBonos", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AutorizarRedencionBonos(ByVal codEstacion As String, ByVal tarjeta As String, ByVal recibo As String, ByVal valor As Decimal, ByVal cantidad As Decimal) As RespuestaRedencionBono
            Dim results() As Object = Me.Invoke("AutorizarRedencionBonos", New Object() {codEstacion, tarjeta, recibo, valor, cantidad})
            Return CType(results(0),RespuestaRedencionBono)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AutorizarRedencionBonosAsync(ByVal codEstacion As String, ByVal tarjeta As String, ByVal recibo As String, ByVal valor As Decimal, ByVal cantidad As Decimal)
            Me.AutorizarRedencionBonosAsync(codEstacion, tarjeta, recibo, valor, cantidad, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AutorizarRedencionBonosAsync(ByVal codEstacion As String, ByVal tarjeta As String, ByVal recibo As String, ByVal valor As Decimal, ByVal cantidad As Decimal, ByVal userState As Object)
            If (Me.AutorizarRedencionBonosOperationCompleted Is Nothing) Then
                Me.AutorizarRedencionBonosOperationCompleted = AddressOf Me.OnAutorizarRedencionBonosOperationCompleted
            End If
            Me.InvokeAsync("AutorizarRedencionBonos", New Object() {codEstacion, tarjeta, recibo, valor, cantidad}, Me.AutorizarRedencionBonosOperationCompleted, userState)
        End Sub
        
        Private Sub OnAutorizarRedencionBonosOperationCompleted(ByVal arg As Object)
            If (Not (Me.AutorizarRedencionBonosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AutorizarRedencionBonosCompleted(Me, New AutorizarRedencionBonosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AutorizarRedencionBonosConIdentificacion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AutorizarRedencionBonosConIdentificacion(ByVal codEstacion As String, ByVal rut As String, ByVal recibo As String, ByVal valor As Decimal, ByVal cantidad As Decimal) As RespuestaRedencionBono
            Dim results() As Object = Me.Invoke("AutorizarRedencionBonosConIdentificacion", New Object() {codEstacion, rut, recibo, valor, cantidad})
            Return CType(results(0),RespuestaRedencionBono)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AutorizarRedencionBonosConIdentificacionAsync(ByVal codEstacion As String, ByVal rut As String, ByVal recibo As String, ByVal valor As Decimal, ByVal cantidad As Decimal)
            Me.AutorizarRedencionBonosConIdentificacionAsync(codEstacion, rut, recibo, valor, cantidad, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AutorizarRedencionBonosConIdentificacionAsync(ByVal codEstacion As String, ByVal rut As String, ByVal recibo As String, ByVal valor As Decimal, ByVal cantidad As Decimal, ByVal userState As Object)
            If (Me.AutorizarRedencionBonosConIdentificacionOperationCompleted Is Nothing) Then
                Me.AutorizarRedencionBonosConIdentificacionOperationCompleted = AddressOf Me.OnAutorizarRedencionBonosConIdentificacionOperationCompleted
            End If
            Me.InvokeAsync("AutorizarRedencionBonosConIdentificacion", New Object() {codEstacion, rut, recibo, valor, cantidad}, Me.AutorizarRedencionBonosConIdentificacionOperationCompleted, userState)
        End Sub
        
        Private Sub OnAutorizarRedencionBonosConIdentificacionOperationCompleted(ByVal arg As Object)
            If (Not (Me.AutorizarRedencionBonosConIdentificacionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AutorizarRedencionBonosConIdentificacionCompleted(Me, New AutorizarRedencionBonosConIdentificacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmacionRedencionBonos", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConfirmacionRedencionBonos(ByVal codEstacion As String, ByVal tarjeta As String, ByVal recibo As String, ByVal idAutorizacionFidelizacion As Long, ByVal idConfirmacionEds As Long, ByVal valor As Decimal) As RespuestaRedencion
            Dim results() As Object = Me.Invoke("ConfirmacionRedencionBonos", New Object() {codEstacion, tarjeta, recibo, idAutorizacionFidelizacion, idConfirmacionEds, valor})
            Return CType(results(0),RespuestaRedencion)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConfirmacionRedencionBonosAsync(ByVal codEstacion As String, ByVal tarjeta As String, ByVal recibo As String, ByVal idAutorizacionFidelizacion As Long, ByVal idConfirmacionEds As Long, ByVal valor As Decimal)
            Me.ConfirmacionRedencionBonosAsync(codEstacion, tarjeta, recibo, idAutorizacionFidelizacion, idConfirmacionEds, valor, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConfirmacionRedencionBonosAsync(ByVal codEstacion As String, ByVal tarjeta As String, ByVal recibo As String, ByVal idAutorizacionFidelizacion As Long, ByVal idConfirmacionEds As Long, ByVal valor As Decimal, ByVal userState As Object)
            If (Me.ConfirmacionRedencionBonosOperationCompleted Is Nothing) Then
                Me.ConfirmacionRedencionBonosOperationCompleted = AddressOf Me.OnConfirmacionRedencionBonosOperationCompleted
            End If
            Me.InvokeAsync("ConfirmacionRedencionBonos", New Object() {codEstacion, tarjeta, recibo, idAutorizacionFidelizacion, idConfirmacionEds, valor}, Me.ConfirmacionRedencionBonosOperationCompleted, userState)
        End Sub
        
        Private Sub OnConfirmacionRedencionBonosOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConfirmacionRedencionBonosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConfirmacionRedencionBonosCompleted(Me, New ConfirmacionRedencionBonosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelarRedencionBonos", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CancelarRedencionBonos(ByVal codEstacion As String, ByVal tarjeta As String, ByVal recibo As String, ByVal valor As Decimal) As RespuestaRedencion
            Dim results() As Object = Me.Invoke("CancelarRedencionBonos", New Object() {codEstacion, tarjeta, recibo, valor})
            Return CType(results(0),RespuestaRedencion)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CancelarRedencionBonosAsync(ByVal codEstacion As String, ByVal tarjeta As String, ByVal recibo As String, ByVal valor As Decimal)
            Me.CancelarRedencionBonosAsync(codEstacion, tarjeta, recibo, valor, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CancelarRedencionBonosAsync(ByVal codEstacion As String, ByVal tarjeta As String, ByVal recibo As String, ByVal valor As Decimal, ByVal userState As Object)
            If (Me.CancelarRedencionBonosOperationCompleted Is Nothing) Then
                Me.CancelarRedencionBonosOperationCompleted = AddressOf Me.OnCancelarRedencionBonosOperationCompleted
            End If
            Me.InvokeAsync("CancelarRedencionBonos", New Object() {codEstacion, tarjeta, recibo, valor}, Me.CancelarRedencionBonosOperationCompleted, userState)
        End Sub
        
        Private Sub OnCancelarRedencionBonosOperationCompleted(ByVal arg As Object)
            If (Not (Me.CancelarRedencionBonosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CancelarRedencionBonosCompleted(Me, New CancelarRedencionBonosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RespuestaFidelizacion
        
        Private mensajesClienteField As System.Data.DataSet
        
        Private mensajeErrorField As String
        
        Private tarjetaField As String
        
        Private saldosField As System.Data.DataSet
        
        Private informacionBonoField As System.Data.DataSet
        
        '''<comentarios/>
        Public Property MensajesCliente() As System.Data.DataSet
            Get
                Return Me.mensajesClienteField
            End Get
            Set
                Me.mensajesClienteField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Tarjeta() As String
            Get
                Return Me.tarjetaField
            End Get
            Set
                Me.tarjetaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Saldos() As System.Data.DataSet
            Get
                Return Me.saldosField
            End Get
            Set
                Me.saldosField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property InformacionBono() As System.Data.DataSet
            Get
                Return Me.informacionBonoField
            End Get
            Set
                Me.informacionBonoField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RespuestaRedencion
        
        Private autorizadoField As Boolean
        
        Private mensajeErrorField As String
        
        '''<comentarios/>
        Public Property Autorizado() As Boolean
            Get
                Return Me.autorizadoField
            End Get
            Set
                Me.autorizadoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RespuestaRedencionBono
        
        Private nroTarjetaField As String
        
        Private idAutorizacionField As Long
        
        Private valorField As Decimal
        
        Private autorizadoField As Boolean
        
        Private mensajeErrorField As String
        
        Private cantidadField As Decimal
        
        Private valorUnitarioPremioField As Decimal
        
        Private puntosCanjeadosField As Decimal
        
        Private cantidadBonosRedimidosField As Long
        
        '''<comentarios/>
        Public Property NroTarjeta() As String
            Get
                Return Me.nroTarjetaField
            End Get
            Set
                Me.nroTarjetaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property IdAutorizacion() As Long
            Get
                Return Me.idAutorizacionField
            End Get
            Set
                Me.idAutorizacionField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Valor() As Decimal
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Autorizado() As Boolean
            Get
                Return Me.autorizadoField
            End Get
            Set
                Me.autorizadoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Cantidad() As Decimal
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ValorUnitarioPremio() As Decimal
            Get
                Return Me.valorUnitarioPremioField
            End Get
            Set
                Me.valorUnitarioPremioField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PuntosCanjeados() As Decimal
            Get
                Return Me.puntosCanjeadosField
            End Get
            Set
                Me.puntosCanjeadosField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CantidadBonosRedimidos() As Long
            Get
                Return Me.cantidadBonosRedimidosField
            End Get
            Set
                Me.cantidadBonosRedimidosField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RespuestaInformacionPremio
        
        Private tarjetaField As String
        
        Private idPremioField As Integer
        
        Private cantidadField As Decimal
        
        Private valorUnitarioPremioField As Decimal
        
        '''<comentarios/>
        Public Property Tarjeta() As String
            Get
                Return Me.tarjetaField
            End Get
            Set
                Me.tarjetaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property IdPremio() As Integer
            Get
                Return Me.idPremioField
            End Get
            Set
                Me.idPremioField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Cantidad() As Decimal
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ValorUnitarioPremio() As Decimal
            Get
                Return Me.valorUnitarioPremioField
            End Get
            Set
                Me.valorUnitarioPremioField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum TipoIdentificadorFidelizacion
        
        '''<comentarios/>
        Tarjeta
        
        '''<comentarios/>
        NroConductor
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub RegistrarVentaFidelizadaCompletedEventHandler(ByVal sender As Object, ByVal e As RegistrarVentaFidelizadaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistrarVentaFidelizadaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub RegistrarVentaFidelizadaPorNroConductorCompletedEventHandler(ByVal sender As Object, ByVal e As RegistrarVentaFidelizadaPorNroConductorCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistrarVentaFidelizadaPorNroConductorCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub ConsultarSaldosTarjetaPorEDSCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarSaldosTarjetaPorEDSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarSaldosTarjetaPorEDSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaFidelizacion
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaFidelizacion)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub ConsultarInformacionPremioBonoCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarInformacionPremioBonoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarInformacionPremioBonoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaInformacionPremio
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaInformacionPremio)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub ConsultarSaldosTarjetaConIdentificacionCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarSaldosTarjetaConIdentificacionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarSaldosTarjetaConIdentificacionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaFidelizacion
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaFidelizacion)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub AutorizarRedencionPremioBonoCompletedEventHandler(ByVal sender As Object, ByVal e As AutorizarRedencionPremioBonoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AutorizarRedencionPremioBonoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaRedencionBono
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaRedencionBono)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub AutorizarRedencionBonosCompletedEventHandler(ByVal sender As Object, ByVal e As AutorizarRedencionBonosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AutorizarRedencionBonosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaRedencionBono
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaRedencionBono)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub AutorizarRedencionBonosConIdentificacionCompletedEventHandler(ByVal sender As Object, ByVal e As AutorizarRedencionBonosConIdentificacionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AutorizarRedencionBonosConIdentificacionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaRedencionBono
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaRedencionBono)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub ConfirmacionRedencionBonosCompletedEventHandler(ByVal sender As Object, ByVal e As ConfirmacionRedencionBonosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConfirmacionRedencionBonosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaRedencion
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaRedencion)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub CancelarRedencionBonosCompletedEventHandler(ByVal sender As Object, ByVal e As CancelarRedencionBonosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CancelarRedencionBonosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaRedencion
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaRedencion)
            End Get
        End Property
    End Class
End Namespace
