'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18034
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18034.
'
Namespace CDIChile
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ComunicacionSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Comunicacion
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private RegistrarVentaEstacionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AutorizarVentaGerenciamientoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AutorizarVentaCreditoManualOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConfirmarVentaGerenciamientoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegistrarTurnoEstacionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegistrarVentaCreditoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarInformacionVentaCreditoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RecuperarMetaMensualOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RecuperarEstadoChipMadreOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.POSstation.ServerServices.My.MySettings.Default.ServerServices_CDIChile_Comunicacion
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event RegistrarVentaEstacionCompleted As RegistrarVentaEstacionCompletedEventHandler
        
        '''<remarks/>
        Public Event AutorizarVentaGerenciamientoCompleted As AutorizarVentaGerenciamientoCompletedEventHandler
        
        '''<remarks/>
        Public Event AutorizarVentaCreditoManualCompleted As AutorizarVentaCreditoManualCompletedEventHandler
        
        '''<remarks/>
        Public Event ConfirmarVentaGerenciamientoCompleted As ConfirmarVentaGerenciamientoCompletedEventHandler
        
        '''<remarks/>
        Public Event RegistrarTurnoEstacionCompleted As RegistrarTurnoEstacionCompletedEventHandler
        
        '''<remarks/>
        Public Event RegistrarVentaCreditoCompleted As RegistrarVentaCreditoCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarInformacionVentaCreditoCompleted As ConsultarInformacionVentaCreditoCompletedEventHandler
        
        '''<remarks/>
        Public Event RecuperarMetaMensualCompleted As RecuperarMetaMensualCompletedEventHandler
        
        '''<remarks/>
        Public Event RecuperarEstadoChipMadreCompleted As RecuperarEstadoChipMadreCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarVentaEstacion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegistrarVentaEstacion(ByVal VentaEds As Venta) As RespuestaCDC
            Dim results() As Object = Me.Invoke("RegistrarVentaEstacion", New Object() {VentaEds})
            Return CType(results(0),RespuestaCDC)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistrarVentaEstacionAsync(ByVal VentaEds As Venta)
            Me.RegistrarVentaEstacionAsync(VentaEds, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistrarVentaEstacionAsync(ByVal VentaEds As Venta, ByVal userState As Object)
            If (Me.RegistrarVentaEstacionOperationCompleted Is Nothing) Then
                Me.RegistrarVentaEstacionOperationCompleted = AddressOf Me.OnRegistrarVentaEstacionOperationCompleted
            End If
            Me.InvokeAsync("RegistrarVentaEstacion", New Object() {VentaEds}, Me.RegistrarVentaEstacionOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistrarVentaEstacionOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegistrarVentaEstacionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistrarVentaEstacionCompleted(Me, New RegistrarVentaEstacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AutorizarVentaGerenciamiento", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AutorizarVentaGerenciamiento(ByVal AutorizacionEds As AutorizacionGerenciamiento) As RespuestaAutorizacionGerenciamiento
            Dim results() As Object = Me.Invoke("AutorizarVentaGerenciamiento", New Object() {AutorizacionEds})
            Return CType(results(0),RespuestaAutorizacionGerenciamiento)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AutorizarVentaGerenciamientoAsync(ByVal AutorizacionEds As AutorizacionGerenciamiento)
            Me.AutorizarVentaGerenciamientoAsync(AutorizacionEds, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AutorizarVentaGerenciamientoAsync(ByVal AutorizacionEds As AutorizacionGerenciamiento, ByVal userState As Object)
            If (Me.AutorizarVentaGerenciamientoOperationCompleted Is Nothing) Then
                Me.AutorizarVentaGerenciamientoOperationCompleted = AddressOf Me.OnAutorizarVentaGerenciamientoOperationCompleted
            End If
            Me.InvokeAsync("AutorizarVentaGerenciamiento", New Object() {AutorizacionEds}, Me.AutorizarVentaGerenciamientoOperationCompleted, userState)
        End Sub
        
        Private Sub OnAutorizarVentaGerenciamientoOperationCompleted(ByVal arg As Object)
            If (Not (Me.AutorizarVentaGerenciamientoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AutorizarVentaGerenciamientoCompleted(Me, New AutorizarVentaGerenciamientoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AutorizarVentaCreditoManual", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AutorizarVentaCreditoManual(ByVal AutorizacionEds As AutorizacionManualCredito) As RespuestaAutorizacionGerenciamiento
            Dim results() As Object = Me.Invoke("AutorizarVentaCreditoManual", New Object() {AutorizacionEds})
            Return CType(results(0),RespuestaAutorizacionGerenciamiento)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AutorizarVentaCreditoManualAsync(ByVal AutorizacionEds As AutorizacionManualCredito)
            Me.AutorizarVentaCreditoManualAsync(AutorizacionEds, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AutorizarVentaCreditoManualAsync(ByVal AutorizacionEds As AutorizacionManualCredito, ByVal userState As Object)
            If (Me.AutorizarVentaCreditoManualOperationCompleted Is Nothing) Then
                Me.AutorizarVentaCreditoManualOperationCompleted = AddressOf Me.OnAutorizarVentaCreditoManualOperationCompleted
            End If
            Me.InvokeAsync("AutorizarVentaCreditoManual", New Object() {AutorizacionEds}, Me.AutorizarVentaCreditoManualOperationCompleted, userState)
        End Sub
        
        Private Sub OnAutorizarVentaCreditoManualOperationCompleted(ByVal arg As Object)
            If (Not (Me.AutorizarVentaCreditoManualCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AutorizarVentaCreditoManualCompleted(Me, New AutorizarVentaCreditoManualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmarVentaGerenciamiento", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConfirmarVentaGerenciamiento(ByVal VentaGerenciaEds As VentaGerencia) As RespuestaCDC
            Dim results() As Object = Me.Invoke("ConfirmarVentaGerenciamiento", New Object() {VentaGerenciaEds})
            Return CType(results(0),RespuestaCDC)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConfirmarVentaGerenciamientoAsync(ByVal VentaGerenciaEds As VentaGerencia)
            Me.ConfirmarVentaGerenciamientoAsync(VentaGerenciaEds, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConfirmarVentaGerenciamientoAsync(ByVal VentaGerenciaEds As VentaGerencia, ByVal userState As Object)
            If (Me.ConfirmarVentaGerenciamientoOperationCompleted Is Nothing) Then
                Me.ConfirmarVentaGerenciamientoOperationCompleted = AddressOf Me.OnConfirmarVentaGerenciamientoOperationCompleted
            End If
            Me.InvokeAsync("ConfirmarVentaGerenciamiento", New Object() {VentaGerenciaEds}, Me.ConfirmarVentaGerenciamientoOperationCompleted, userState)
        End Sub
        
        Private Sub OnConfirmarVentaGerenciamientoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConfirmarVentaGerenciamientoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConfirmarVentaGerenciamientoCompleted(Me, New ConfirmarVentaGerenciamientoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarTurnoEstacion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegistrarTurnoEstacion(ByVal TurnoEds As Turno) As RespuestaCDC
            Dim results() As Object = Me.Invoke("RegistrarTurnoEstacion", New Object() {TurnoEds})
            Return CType(results(0),RespuestaCDC)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistrarTurnoEstacionAsync(ByVal TurnoEds As Turno)
            Me.RegistrarTurnoEstacionAsync(TurnoEds, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistrarTurnoEstacionAsync(ByVal TurnoEds As Turno, ByVal userState As Object)
            If (Me.RegistrarTurnoEstacionOperationCompleted Is Nothing) Then
                Me.RegistrarTurnoEstacionOperationCompleted = AddressOf Me.OnRegistrarTurnoEstacionOperationCompleted
            End If
            Me.InvokeAsync("RegistrarTurnoEstacion", New Object() {TurnoEds}, Me.RegistrarTurnoEstacionOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistrarTurnoEstacionOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegistrarTurnoEstacionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistrarTurnoEstacionCompleted(Me, New RegistrarTurnoEstacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarVentaCredito", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegistrarVentaCredito(ByVal VentaCredito As VentaCredito) As RespuestaCDC
            Dim results() As Object = Me.Invoke("RegistrarVentaCredito", New Object() {VentaCredito})
            Return CType(results(0),RespuestaCDC)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistrarVentaCreditoAsync(ByVal VentaCredito As VentaCredito)
            Me.RegistrarVentaCreditoAsync(VentaCredito, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistrarVentaCreditoAsync(ByVal VentaCredito As VentaCredito, ByVal userState As Object)
            If (Me.RegistrarVentaCreditoOperationCompleted Is Nothing) Then
                Me.RegistrarVentaCreditoOperationCompleted = AddressOf Me.OnRegistrarVentaCreditoOperationCompleted
            End If
            Me.InvokeAsync("RegistrarVentaCredito", New Object() {VentaCredito}, Me.RegistrarVentaCreditoOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistrarVentaCreditoOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegistrarVentaCreditoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistrarVentaCreditoCompleted(Me, New RegistrarVentaCreditoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarInformacionVentaCredito", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarInformacionVentaCredito(ByVal Placa As String) As RespuestaVentaCredito
            Dim results() As Object = Me.Invoke("ConsultarInformacionVentaCredito", New Object() {Placa})
            Return CType(results(0),RespuestaVentaCredito)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarInformacionVentaCreditoAsync(ByVal Placa As String)
            Me.ConsultarInformacionVentaCreditoAsync(Placa, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarInformacionVentaCreditoAsync(ByVal Placa As String, ByVal userState As Object)
            If (Me.ConsultarInformacionVentaCreditoOperationCompleted Is Nothing) Then
                Me.ConsultarInformacionVentaCreditoOperationCompleted = AddressOf Me.OnConsultarInformacionVentaCreditoOperationCompleted
            End If
            Me.InvokeAsync("ConsultarInformacionVentaCredito", New Object() {Placa}, Me.ConsultarInformacionVentaCreditoOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarInformacionVentaCreditoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarInformacionVentaCreditoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarInformacionVentaCreditoCompleted(Me, New ConsultarInformacionVentaCreditoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarMetaMensual", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RecuperarMetaMensual(ByVal Placa As String) As MentaMensual
            Dim results() As Object = Me.Invoke("RecuperarMetaMensual", New Object() {Placa})
            Return CType(results(0),MentaMensual)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RecuperarMetaMensualAsync(ByVal Placa As String)
            Me.RecuperarMetaMensualAsync(Placa, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RecuperarMetaMensualAsync(ByVal Placa As String, ByVal userState As Object)
            If (Me.RecuperarMetaMensualOperationCompleted Is Nothing) Then
                Me.RecuperarMetaMensualOperationCompleted = AddressOf Me.OnRecuperarMetaMensualOperationCompleted
            End If
            Me.InvokeAsync("RecuperarMetaMensual", New Object() {Placa}, Me.RecuperarMetaMensualOperationCompleted, userState)
        End Sub
        
        Private Sub OnRecuperarMetaMensualOperationCompleted(ByVal arg As Object)
            If (Not (Me.RecuperarMetaMensualCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RecuperarMetaMensualCompleted(Me, New RecuperarMetaMensualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarEstadoChipMadre", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RecuperarEstadoChipMadre(ByVal ROM As String) As EstadoChipMadre
            Dim results() As Object = Me.Invoke("RecuperarEstadoChipMadre", New Object() {ROM})
            Return CType(results(0),EstadoChipMadre)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RecuperarEstadoChipMadreAsync(ByVal ROM As String)
            Me.RecuperarEstadoChipMadreAsync(ROM, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RecuperarEstadoChipMadreAsync(ByVal ROM As String, ByVal userState As Object)
            If (Me.RecuperarEstadoChipMadreOperationCompleted Is Nothing) Then
                Me.RecuperarEstadoChipMadreOperationCompleted = AddressOf Me.OnRecuperarEstadoChipMadreOperationCompleted
            End If
            Me.InvokeAsync("RecuperarEstadoChipMadre", New Object() {ROM}, Me.RecuperarEstadoChipMadreOperationCompleted, userState)
        End Sub
        
        Private Sub OnRecuperarEstadoChipMadreOperationCompleted(ByVal arg As Object)
            If (Not (Me.RecuperarEstadoChipMadreCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RecuperarEstadoChipMadreCompleted(Me, New RecuperarEstadoChipMadreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Venta
        
        Private reciboField As Long
        
        Private idFormaPagoField As Short
        
        Private fechaHoraField As Date
        
        Private idTurnoField As Integer
        
        Private idMangueraField As Short
        
        Private horaInicioField As Date
        
        Private horaFinField As Date
        
        Private lecturaInicialField As Decimal
        
        Private lecturaFinalField As Decimal
        
        Private precioField As Decimal
        
        Private ivaField As Decimal
        
        Private abonoCreditoField As Decimal
        
        Private idClienteField As Integer
        
        Private cantidadField As Decimal
        
        Private valorField As Decimal
        
        Private descuentoField As Decimal
        
        Private placaField As String
        
        Private idProductoField As Integer
        
        Private codEstacionField As String
        
        Private ventasFormaPagoField() As VentaFormaPago
        
        Private idUnidadMedidaField As Short
        
        Private idHistoricoPrecioField As Integer
        
        Private romField As String
        
        Private idIslaField As Integer
        
        Private idCaraField As Integer
        
        Private fechaProximoMantenimientoField As Date
        
        Private idSurtidorField As Short
        
        Private rUTconductorField As String
        
        Private kilometrajeField As String
        
        Private idValeField As System.Nullable(Of Integer)
        
        Private idCuponField As System.Nullable(Of Long)
        
        Private nroFacturaField As String
        
        '''<remarks/>
        Public Property Recibo() As Long
            Get
                Return Me.reciboField
            End Get
            Set
                Me.reciboField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdFormaPago() As Short
            Get
                Return Me.idFormaPagoField
            End Get
            Set
                Me.idFormaPagoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaHora() As Date
            Get
                Return Me.fechaHoraField
            End Get
            Set
                Me.fechaHoraField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdTurno() As Integer
            Get
                Return Me.idTurnoField
            End Get
            Set
                Me.idTurnoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdManguera() As Short
            Get
                Return Me.idMangueraField
            End Get
            Set
                Me.idMangueraField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HoraInicio() As Date
            Get
                Return Me.horaInicioField
            End Get
            Set
                Me.horaInicioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HoraFin() As Date
            Get
                Return Me.horaFinField
            End Get
            Set
                Me.horaFinField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LecturaInicial() As Decimal
            Get
                Return Me.lecturaInicialField
            End Get
            Set
                Me.lecturaInicialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LecturaFinal() As Decimal
            Get
                Return Me.lecturaFinalField
            End Get
            Set
                Me.lecturaFinalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Precio() As Decimal
            Get
                Return Me.precioField
            End Get
            Set
                Me.precioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Iva() As Decimal
            Get
                Return Me.ivaField
            End Get
            Set
                Me.ivaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AbonoCredito() As Decimal
            Get
                Return Me.abonoCreditoField
            End Get
            Set
                Me.abonoCreditoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdCliente() As Integer
            Get
                Return Me.idClienteField
            End Get
            Set
                Me.idClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cantidad() As Decimal
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Valor() As Decimal
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Descuento() As Decimal
            Get
                Return Me.descuentoField
            End Get
            Set
                Me.descuentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Placa() As String
            Get
                Return Me.placaField
            End Get
            Set
                Me.placaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdProducto() As Integer
            Get
                Return Me.idProductoField
            End Get
            Set
                Me.idProductoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodEstacion() As String
            Get
                Return Me.codEstacionField
            End Get
            Set
                Me.codEstacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VentasFormaPago() As VentaFormaPago()
            Get
                Return Me.ventasFormaPagoField
            End Get
            Set
                Me.ventasFormaPagoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdUnidadMedida() As Short
            Get
                Return Me.idUnidadMedidaField
            End Get
            Set
                Me.idUnidadMedidaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdHistoricoPrecio() As Integer
            Get
                Return Me.idHistoricoPrecioField
            End Get
            Set
                Me.idHistoricoPrecioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Rom() As String
            Get
                Return Me.romField
            End Get
            Set
                Me.romField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdIsla() As Integer
            Get
                Return Me.idIslaField
            End Get
            Set
                Me.idIslaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdCara() As Integer
            Get
                Return Me.idCaraField
            End Get
            Set
                Me.idCaraField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaProximoMantenimiento() As Date
            Get
                Return Me.fechaProximoMantenimientoField
            End Get
            Set
                Me.fechaProximoMantenimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdSurtidor() As Short
            Get
                Return Me.idSurtidorField
            End Get
            Set
                Me.idSurtidorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RUTconductor() As String
            Get
                Return Me.rUTconductorField
            End Get
            Set
                Me.rUTconductorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Kilometraje() As String
            Get
                Return Me.kilometrajeField
            End Get
            Set
                Me.kilometrajeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property IdVale() As System.Nullable(Of Integer)
            Get
                Return Me.idValeField
            End Get
            Set
                Me.idValeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property IdCupon() As System.Nullable(Of Long)
            Get
                Return Me.idCuponField
            End Get
            Set
                Me.idCuponField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NroFactura() As String
            Get
                Return Me.nroFacturaField
            End Get
            Set
                Me.nroFacturaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class VentaFormaPago
        
        Private idMedioPagoField As Integer
        
        Private totalField As Decimal
        
        '''<remarks/>
        Public Property IdMedioPago() As Integer
            Get
                Return Me.idMedioPagoField
            End Get
            Set
                Me.idMedioPagoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Total() As Decimal
            Get
                Return Me.totalField
            End Get
            Set
                Me.totalField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EstadoChipMadre
        
        Private mensajeErrorField As String
        
        Private esProcesadoField As Boolean
        
        Private estadoChipMadreEstacionField As Integer
        
        '''<remarks/>
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EsProcesado() As Boolean
            Get
                Return Me.esProcesadoField
            End Get
            Set
                Me.esProcesadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EstadoChipMadreEstacion() As Integer
            Get
                Return Me.estadoChipMadreEstacionField
            End Get
            Set
                Me.estadoChipMadreEstacionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class MentaMensual
        
        Private mensajeErrorField As String
        
        Private esProcesadoField As Boolean
        
        Private metaMensualField As Decimal
        
        Private acumuladoMesField As String
        
        '''<remarks/>
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EsProcesado() As Boolean
            Get
                Return Me.esProcesadoField
            End Get
            Set
                Me.esProcesadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MetaMensual() As Decimal
            Get
                Return Me.metaMensualField
            End Get
            Set
                Me.metaMensualField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AcumuladoMes() As String
            Get
                Return Me.acumuladoMesField
            End Get
            Set
                Me.acumuladoMesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RespuestaVentaCredito
        
        Private copagoRestanteField As Decimal
        
        Private copagoAcumuladoField As Decimal
        
        Private mensajeErrorField As String
        
        Private esProcesadoField As Boolean
        
        '''<remarks/>
        Public Property CopagoRestante() As Decimal
            Get
                Return Me.copagoRestanteField
            End Get
            Set
                Me.copagoRestanteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CopagoAcumulado() As Decimal
            Get
                Return Me.copagoAcumuladoField
            End Get
            Set
                Me.copagoAcumuladoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EsProcesado() As Boolean
            Get
                Return Me.esProcesadoField
            End Get
            Set
                Me.esProcesadoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class VentaCredito
        
        Private codEstacionField As String
        
        Private reciboField As Long
        
        Private creditoField As Integer
        
        Private porcentajeField As Decimal
        
        Private valorField As Decimal
        
        Private idTipoRecaudoField As Integer
        
        Private valorTipoRecaudoField As Decimal
        
        '''<remarks/>
        Public Property CodEstacion() As String
            Get
                Return Me.codEstacionField
            End Get
            Set
                Me.codEstacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Recibo() As Long
            Get
                Return Me.reciboField
            End Get
            Set
                Me.reciboField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Credito() As Integer
            Get
                Return Me.creditoField
            End Get
            Set
                Me.creditoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Porcentaje() As Decimal
            Get
                Return Me.porcentajeField
            End Get
            Set
                Me.porcentajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Valor() As Decimal
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdTipoRecaudo() As Integer
            Get
                Return Me.idTipoRecaudoField
            End Get
            Set
                Me.idTipoRecaudoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ValorTipoRecaudo() As Decimal
            Get
                Return Me.valorTipoRecaudoField
            End Get
            Set
                Me.valorTipoRecaudoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class LecturaManguera
        
        Private idMangueraField As Short
        
        Private lecturaInicialField As Decimal
        
        Private lecturaFinalField As Decimal
        
        '''<remarks/>
        Public Property IdManguera() As Short
            Get
                Return Me.idMangueraField
            End Get
            Set
                Me.idMangueraField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LecturaInicial() As Decimal
            Get
                Return Me.lecturaInicialField
            End Get
            Set
                Me.lecturaInicialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LecturaFinal() As Decimal
            Get
                Return Me.lecturaFinalField
            End Get
            Set
                Me.lecturaFinalField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Producto
        
        Private idProductoField As Integer
        
        Private precioField As Decimal
        
        '''<remarks/>
        Public Property IdProducto() As Integer
            Get
                Return Me.idProductoField
            End Get
            Set
                Me.idProductoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Precio() As Decimal
            Get
                Return Me.precioField
            End Get
            Set
                Me.precioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Turno
        
        Private idTurnoField As Integer
        
        Private codEstacionField As String
        
        Private idEmpleadoField As Integer
        
        Private fechaAperturaField As Date
        
        Private fechaCierreField As Date
        
        Private productosField() As Producto
        
        Private lecturasMangueraField() As LecturaManguera
        
        Private numeroturnoField As Short
        
        '''<remarks/>
        Public Property IdTurno() As Integer
            Get
                Return Me.idTurnoField
            End Get
            Set
                Me.idTurnoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodEstacion() As String
            Get
                Return Me.codEstacionField
            End Get
            Set
                Me.codEstacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdEmpleado() As Integer
            Get
                Return Me.idEmpleadoField
            End Get
            Set
                Me.idEmpleadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaApertura() As Date
            Get
                Return Me.fechaAperturaField
            End Get
            Set
                Me.fechaAperturaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaCierre() As Date
            Get
                Return Me.fechaCierreField
            End Get
            Set
                Me.fechaCierreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Productos() As Producto()
            Get
                Return Me.productosField
            End Get
            Set
                Me.productosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LecturasManguera() As LecturaManguera()
            Get
                Return Me.lecturasMangueraField
            End Get
            Set
                Me.lecturasMangueraField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Numeroturno() As Short
            Get
                Return Me.numeroturnoField
            End Get
            Set
                Me.numeroturnoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class VentaGerencia
        
        Private idAutorizacionCDCField As Long
        
        Private codEstacionField As String
        
        Private kilometrajeField As String
        
        Private reciboEdsField As Long
        
        '''<remarks/>
        Public Property IdAutorizacionCDC() As Long
            Get
                Return Me.idAutorizacionCDCField
            End Get
            Set
                Me.idAutorizacionCDCField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodEstacion() As String
            Get
                Return Me.codEstacionField
            End Get
            Set
                Me.codEstacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Kilometraje() As String
            Get
                Return Me.kilometrajeField
            End Get
            Set
                Me.kilometrajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReciboEds() As Long
            Get
                Return Me.reciboEdsField
            End Get
            Set
                Me.reciboEdsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AutorizacionManualCredito
        
        Private reciboField As Long
        
        Private codEstacionField As String
        
        Private nroGuiaDespachoField As String
        
        Private identificacionClienteField As String
        
        Private placaField As String
        
        Private rOMField As String
        
        '''<remarks/>
        Public Property Recibo() As Long
            Get
                Return Me.reciboField
            End Get
            Set
                Me.reciboField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodEstacion() As String
            Get
                Return Me.codEstacionField
            End Get
            Set
                Me.codEstacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NroGuiaDespacho() As String
            Get
                Return Me.nroGuiaDespachoField
            End Get
            Set
                Me.nroGuiaDespachoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdentificacionCliente() As String
            Get
                Return Me.identificacionClienteField
            End Get
            Set
                Me.identificacionClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Placa() As String
            Get
                Return Me.placaField
            End Get
            Set
                Me.placaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ROM() As String
            Get
                Return Me.rOMField
            End Get
            Set
                Me.rOMField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RespuestaAutorizacionGerenciamiento
        
        Private idAutorizacionField As Long
        
        Private idFormaPagoField As Short
        
        Private valorAutorizadoField As Decimal
        
        Private saldoDisponibleField As Decimal
        
        Private mensajeErrorField As String
        
        Private esAutorizadoField As Boolean
        
        Private consumoMesField As Double
        
        '''<remarks/>
        Public Property IdAutorizacion() As Long
            Get
                Return Me.idAutorizacionField
            End Get
            Set
                Me.idAutorizacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdFormaPago() As Short
            Get
                Return Me.idFormaPagoField
            End Get
            Set
                Me.idFormaPagoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ValorAutorizado() As Decimal
            Get
                Return Me.valorAutorizadoField
            End Get
            Set
                Me.valorAutorizadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SaldoDisponible() As Decimal
            Get
                Return Me.saldoDisponibleField
            End Get
            Set
                Me.saldoDisponibleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EsAutorizado() As Boolean
            Get
                Return Me.esAutorizadoField
            End Get
            Set
                Me.esAutorizadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ConsumoMes() As Double
            Get
                Return Me.consumoMesField
            End Get
            Set
                Me.consumoMesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AutorizacionGerenciamiento
        
        Private placaField As String
        
        Private identificacionField As String
        
        Private precioField As Decimal
        
        Private codEstacionField As String
        
        Private idProductoField As Integer
        
        Private kilometrajeField As String
        
        Private rUCConductorField As String
        
        '''<remarks/>
        Public Property Placa() As String
            Get
                Return Me.placaField
            End Get
            Set
                Me.placaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Identificacion() As String
            Get
                Return Me.identificacionField
            End Get
            Set
                Me.identificacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Precio() As Decimal
            Get
                Return Me.precioField
            End Get
            Set
                Me.precioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodEstacion() As String
            Get
                Return Me.codEstacionField
            End Get
            Set
                Me.codEstacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdProducto() As Integer
            Get
                Return Me.idProductoField
            End Get
            Set
                Me.idProductoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Kilometraje() As String
            Get
                Return Me.kilometrajeField
            End Get
            Set
                Me.kilometrajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RUCConductor() As String
            Get
                Return Me.rUCConductorField
            End Get
            Set
                Me.rUCConductorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RespuestaCDC
        
        Private mensajeErrorField As String
        
        Private esProcesadoField As Boolean
        
        '''<remarks/>
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EsProcesado() As Boolean
            Get
                Return Me.esProcesadoField
            End Get
            Set
                Me.esProcesadoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub RegistrarVentaEstacionCompletedEventHandler(ByVal sender As Object, ByVal e As RegistrarVentaEstacionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistrarVentaEstacionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaCDC
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaCDC)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub AutorizarVentaGerenciamientoCompletedEventHandler(ByVal sender As Object, ByVal e As AutorizarVentaGerenciamientoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AutorizarVentaGerenciamientoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaAutorizacionGerenciamiento
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaAutorizacionGerenciamiento)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub AutorizarVentaCreditoManualCompletedEventHandler(ByVal sender As Object, ByVal e As AutorizarVentaCreditoManualCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AutorizarVentaCreditoManualCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaAutorizacionGerenciamiento
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaAutorizacionGerenciamiento)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub ConfirmarVentaGerenciamientoCompletedEventHandler(ByVal sender As Object, ByVal e As ConfirmarVentaGerenciamientoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConfirmarVentaGerenciamientoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaCDC
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaCDC)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub RegistrarTurnoEstacionCompletedEventHandler(ByVal sender As Object, ByVal e As RegistrarTurnoEstacionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistrarTurnoEstacionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaCDC
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaCDC)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub RegistrarVentaCreditoCompletedEventHandler(ByVal sender As Object, ByVal e As RegistrarVentaCreditoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistrarVentaCreditoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaCDC
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaCDC)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub ConsultarInformacionVentaCreditoCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarInformacionVentaCreditoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarInformacionVentaCreditoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaVentaCredito
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaVentaCredito)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub RecuperarMetaMensualCompletedEventHandler(ByVal sender As Object, ByVal e As RecuperarMetaMensualCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RecuperarMetaMensualCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MentaMensual
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MentaMensual)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub RecuperarEstadoChipMadreCompletedEventHandler(ByVal sender As Object, ByVal e As RecuperarEstadoChipMadreCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RecuperarEstadoChipMadreCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As EstadoChipMadre
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),EstadoChipMadre)
            End Get
        End Property
    End Class
End Namespace
