'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34014
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34014.
'
Namespace CDCTerpel
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="IntegratorSoap", [Namespace]:="http://GNC.CDC/ServiciosVentaGasSL")>  _
    Partial Public Class Integrator
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private AutorizacionSuministroSLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegistrarVentaGasSLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CerrarDiaSLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private LiberarAutorizacionesSLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaFaltantesSLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New

            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event AutorizacionSuministroSLCompleted As AutorizacionSuministroSLCompletedEventHandler
        
        '''<remarks/>
        Public Event RegistrarVentaGasSLCompleted As RegistrarVentaGasSLCompletedEventHandler
        
        '''<remarks/>
        Public Event CerrarDiaSLCompleted As CerrarDiaSLCompletedEventHandler
        
        '''<remarks/>
        Public Event LiberarAutorizacionesSLCompleted As LiberarAutorizacionesSLCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaFaltantesSLCompleted As ConsultaFaltantesSLCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://GNC.CDC/ServiciosVentaGasSL/AutorizacionSuministroSL", RequestNamespace:="http://GNC.CDC/ServiciosVentaGasSL", ResponseNamespace:="http://GNC.CDC/ServiciosVentaGasSL", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AutorizacionSuministroSL(ByVal Solicitud As String) As AutorizacionSuministroSLResult
            Dim results() As Object = Me.Invoke("AutorizacionSuministroSL", New Object() {Solicitud})
            Return CType(results(0),AutorizacionSuministroSLResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AutorizacionSuministroSLAsync(ByVal Solicitud As String)
            Me.AutorizacionSuministroSLAsync(Solicitud, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AutorizacionSuministroSLAsync(ByVal Solicitud As String, ByVal userState As Object)
            If (Me.AutorizacionSuministroSLOperationCompleted Is Nothing) Then
                Me.AutorizacionSuministroSLOperationCompleted = AddressOf Me.OnAutorizacionSuministroSLOperationCompleted
            End If
            Me.InvokeAsync("AutorizacionSuministroSL", New Object() {Solicitud}, Me.AutorizacionSuministroSLOperationCompleted, userState)
        End Sub
        
        Private Sub OnAutorizacionSuministroSLOperationCompleted(ByVal arg As Object)
            If (Not (Me.AutorizacionSuministroSLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AutorizacionSuministroSLCompleted(Me, New AutorizacionSuministroSLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://GNC.CDC/ServiciosVentaGasSL/RegistrarVentaGasSL", RequestNamespace:="http://GNC.CDC/ServiciosVentaGasSL", ResponseNamespace:="http://GNC.CDC/ServiciosVentaGasSL", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegistrarVentaGasSL(ByVal VentaGasSL As String) As String
            Dim results() As Object = Me.Invoke("RegistrarVentaGasSL", New Object() {VentaGasSL})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistrarVentaGasSLAsync(ByVal VentaGasSL As String)
            Me.RegistrarVentaGasSLAsync(VentaGasSL, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistrarVentaGasSLAsync(ByVal VentaGasSL As String, ByVal userState As Object)
            If (Me.RegistrarVentaGasSLOperationCompleted Is Nothing) Then
                Me.RegistrarVentaGasSLOperationCompleted = AddressOf Me.OnRegistrarVentaGasSLOperationCompleted
            End If
            Me.InvokeAsync("RegistrarVentaGasSL", New Object() {VentaGasSL}, Me.RegistrarVentaGasSLOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistrarVentaGasSLOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegistrarVentaGasSLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistrarVentaGasSLCompleted(Me, New RegistrarVentaGasSLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://GNC.CDC/ServiciosVentaGasSL/CerrarDiaSL", RequestNamespace:="http://GNC.CDC/ServiciosVentaGasSL", ResponseNamespace:="http://GNC.CDC/ServiciosVentaGasSL", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CerrarDiaSL(ByVal cierre As String) As String
            Dim results() As Object = Me.Invoke("CerrarDiaSL", New Object() {cierre})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CerrarDiaSLAsync(ByVal cierre As String)
            Me.CerrarDiaSLAsync(cierre, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CerrarDiaSLAsync(ByVal cierre As String, ByVal userState As Object)
            If (Me.CerrarDiaSLOperationCompleted Is Nothing) Then
                Me.CerrarDiaSLOperationCompleted = AddressOf Me.OnCerrarDiaSLOperationCompleted
            End If
            Me.InvokeAsync("CerrarDiaSL", New Object() {cierre}, Me.CerrarDiaSLOperationCompleted, userState)
        End Sub
        
        Private Sub OnCerrarDiaSLOperationCompleted(ByVal arg As Object)
            If (Not (Me.CerrarDiaSLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CerrarDiaSLCompleted(Me, New CerrarDiaSLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://GNC.CDC/ServiciosVentaGasSL/LiberarAutorizacionesSL", RequestNamespace:="http://GNC.CDC/ServiciosVentaGasSL", ResponseNamespace:="http://GNC.CDC/ServiciosVentaGasSL", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LiberarAutorizacionesSL(ByVal autorizacionesLibres As String) As String
            Dim results() As Object = Me.Invoke("LiberarAutorizacionesSL", New Object() {autorizacionesLibres})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LiberarAutorizacionesSLAsync(ByVal autorizacionesLibres As String)
            Me.LiberarAutorizacionesSLAsync(autorizacionesLibres, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LiberarAutorizacionesSLAsync(ByVal autorizacionesLibres As String, ByVal userState As Object)
            If (Me.LiberarAutorizacionesSLOperationCompleted Is Nothing) Then
                Me.LiberarAutorizacionesSLOperationCompleted = AddressOf Me.OnLiberarAutorizacionesSLOperationCompleted
            End If
            Me.InvokeAsync("LiberarAutorizacionesSL", New Object() {autorizacionesLibres}, Me.LiberarAutorizacionesSLOperationCompleted, userState)
        End Sub
        
        Private Sub OnLiberarAutorizacionesSLOperationCompleted(ByVal arg As Object)
            If (Not (Me.LiberarAutorizacionesSLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LiberarAutorizacionesSLCompleted(Me, New LiberarAutorizacionesSLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://GNC.CDC/ServiciosVentaGasSL/ConsultaFaltantesSL", RequestNamespace:="http://GNC.CDC/ServiciosVentaGasSL", ResponseNamespace:="http://GNC.CDC/ServiciosVentaGasSL", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultaFaltantesSL(ByVal Solicitud As String) As ListaConsecutivosFaltantes
            Dim results() As Object = Me.Invoke("ConsultaFaltantesSL", New Object() {Solicitud})
            Return CType(results(0),ListaConsecutivosFaltantes)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaFaltantesSLAsync(ByVal Solicitud As String)
            Me.ConsultaFaltantesSLAsync(Solicitud, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaFaltantesSLAsync(ByVal Solicitud As String, ByVal userState As Object)
            If (Me.ConsultaFaltantesSLOperationCompleted Is Nothing) Then
                Me.ConsultaFaltantesSLOperationCompleted = AddressOf Me.OnConsultaFaltantesSLOperationCompleted
            End If
            Me.InvokeAsync("ConsultaFaltantesSL", New Object() {Solicitud}, Me.ConsultaFaltantesSLOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaFaltantesSLOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaFaltantesSLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaFaltantesSLCompleted(Me, New ConsultaFaltantesSLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://Terpel.CDC/AutorizacionVentaSL.xsd")>  _
    Partial Public Class AutorizacionSuministroSLResult
        
        Private iaField As Integer
        
        Private mField As String
        
        Private iFPField As Integer
        
        Private cMVField As Decimal
        
        Private cMDField As Decimal
        
        Private sdField As Decimal
        
        Private ncField As String
        
        Private niField As String
        
        Private pField As String
        
        Private vIIField As Decimal
        
        '''<comentarios/>
        Public Property IA() As Integer
            Get
                Return Me.iaField
            End Get
            Set
                Me.iaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property M() As String
            Get
                Return Me.mField
            End Get
            Set
                Me.mField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property IFP() As Integer
            Get
                Return Me.iFPField
            End Get
            Set
                Me.iFPField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CMV() As Decimal
            Get
                Return Me.cMVField
            End Get
            Set
                Me.cMVField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CMD() As Decimal
            Get
                Return Me.cMDField
            End Get
            Set
                Me.cMDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SD() As Decimal
            Get
                Return Me.sdField
            End Get
            Set
                Me.sdField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property NC() As String
            Get
                Return Me.ncField
            End Get
            Set
                Me.ncField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property NI() As String
            Get
                Return Me.niField
            End Get
            Set
                Me.niField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property P() As String
            Get
                Return Me.pField
            End Get
            Set
                Me.pField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property VII() As Decimal
            Get
                Return Me.vIIField
            End Get
            Set
                Me.vIIField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://GNC.CDC/ServiciosVentaGasSL")>  _
    Partial Public Class ConsecutivosFaltantes
        
        Private cODEDSField As Integer
        
        Private iaField() As Integer
        
        Private itField() As Integer
        
        '''<comentarios/>
        Public Property CODEDS() As Integer
            Get
                Return Me.cODEDSField
            End Get
            Set
                Me.cODEDSField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property IA() As Integer()
            Get
                Return Me.iaField
            End Get
            Set
                Me.iaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property IT() As Integer()
            Get
                Return Me.itField
            End Get
            Set
                Me.itField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://GNC.CDC/ServiciosVentaGasSL")>  _
    Partial Public Class ListaConsecutivosFaltantes
        
        Private consecutivosField() As ConsecutivosFaltantes
        
        '''<comentarios/>
        Public Property consecutivos() As ConsecutivosFaltantes()
            Get
                Return Me.consecutivosField
            End Get
            Set
                Me.consecutivosField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub AutorizacionSuministroSLCompletedEventHandler(ByVal sender As Object, ByVal e As AutorizacionSuministroSLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AutorizacionSuministroSLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As AutorizacionSuministroSLResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),AutorizacionSuministroSLResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub RegistrarVentaGasSLCompletedEventHandler(ByVal sender As Object, ByVal e As RegistrarVentaGasSLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistrarVentaGasSLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub CerrarDiaSLCompletedEventHandler(ByVal sender As Object, ByVal e As CerrarDiaSLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CerrarDiaSLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub LiberarAutorizacionesSLCompletedEventHandler(ByVal sender As Object, ByVal e As LiberarAutorizacionesSLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LiberarAutorizacionesSLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub ConsultaFaltantesSLCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaFaltantesSLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaFaltantesSLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ListaConsecutivosFaltantes
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ListaConsecutivosFaltantes)
            End Get
        End Property
    End Class
End Namespace
