'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18034
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18034.
'
Namespace CDCPGN
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ClubpgnBinding", [Namespace]:="http://pgn.com.pe/pgn-network")>  _
    Partial Public Class ClubpgnService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private pgnSolicitudOperationCompleted As System.Threading.SendOrPostCallback
        
        Private pgnTarjetaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.POSstation.ServerServices.My.MySettings.Default.ServerServices_CDCPGN_ClubpgnService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event pgnSolicitudCompleted As pgnSolicitudCompletedEventHandler
        
        '''<remarks/>
        Public Event pgnTarjetaCompleted As pgnTarjetaCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function pgnSolicitud(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://pgn.com.pe/pgn-network")> ByVal pgnSolicitudRequest As pgnSolicitudRequest) As <System.Xml.Serialization.XmlElementAttribute("pgnSolicitudResponse", [Namespace]:="http://pgn.com.pe/pgn-network")> pgnSolicitudResponse
            Dim results() As Object = Me.Invoke("pgnSolicitud", New Object() {pgnSolicitudRequest})
            Return CType(results(0),pgnSolicitudResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub pgnSolicitudAsync(ByVal pgnSolicitudRequest As pgnSolicitudRequest)
            Me.pgnSolicitudAsync(pgnSolicitudRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub pgnSolicitudAsync(ByVal pgnSolicitudRequest As pgnSolicitudRequest, ByVal userState As Object)
            If (Me.pgnSolicitudOperationCompleted Is Nothing) Then
                Me.pgnSolicitudOperationCompleted = AddressOf Me.OnpgnSolicitudOperationCompleted
            End If
            Me.InvokeAsync("pgnSolicitud", New Object() {pgnSolicitudRequest}, Me.pgnSolicitudOperationCompleted, userState)
        End Sub
        
        Private Sub OnpgnSolicitudOperationCompleted(ByVal arg As Object)
            If (Not (Me.pgnSolicitudCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent pgnSolicitudCompleted(Me, New pgnSolicitudCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function pgnTarjeta(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://pgn.com.pe/pgn-network")> ByVal pgnTarjetaRequest As pgnTarjetaRequest) As <System.Xml.Serialization.XmlElementAttribute("pgnTarjetaResponse", [Namespace]:="http://pgn.com.pe/pgn-network")> pgnTarjetaResponse
            Dim results() As Object = Me.Invoke("pgnTarjeta", New Object() {pgnTarjetaRequest})
            Return CType(results(0),pgnTarjetaResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub pgnTarjetaAsync(ByVal pgnTarjetaRequest As pgnTarjetaRequest)
            Me.pgnTarjetaAsync(pgnTarjetaRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub pgnTarjetaAsync(ByVal pgnTarjetaRequest As pgnTarjetaRequest, ByVal userState As Object)
            If (Me.pgnTarjetaOperationCompleted Is Nothing) Then
                Me.pgnTarjetaOperationCompleted = AddressOf Me.OnpgnTarjetaOperationCompleted
            End If
            Me.InvokeAsync("pgnTarjeta", New Object() {pgnTarjetaRequest}, Me.pgnTarjetaOperationCompleted, userState)
        End Sub
        
        Private Sub OnpgnTarjetaOperationCompleted(ByVal arg As Object)
            If (Not (Me.pgnTarjetaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent pgnTarjetaCompleted(Me, New pgnTarjetaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://pgn.com.pe/pgn-network")>  _
    Partial Public Class pgnSolicitudRequest
        
        Private solicitudField As SolicitudType
        
        '''<remarks/>
        Public Property solicitud() As SolicitudType
            Get
                Return Me.solicitudField
            End Get
            Set
                Me.solicitudField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://pgn.com.pe/pgn-network")>  _
    Partial Public Class SolicitudType
        
        Private codeMangueraField As String
        
        Private codeCaraField As String
        
        Private codeSurtidorField As String
        
        Private codeIslaField As String
        
        Private codeEstacionField As String
        
        Private serieField As String
        
        Private numeroField As String
        
        Private codeSerialImpresoraField As String
        
        Private codeTurnoHorarioField As String
        
        Private fechaVentaField As String
        
        Private fechaProcesoField As String
        
        Private fechaAperturaField As String
        
        Private fechaLecturaInicioField As String
        
        Private fechaLecturaFinField As String
        
        Private lecturaInicioField As String
        
        Private lecturaFinalField As String
        
        Private rucField As String
        
        Private productoField As String
        
        Private cantidadField As String
        
        Private precioUnitarioField As String
        
        Private valorVentaField As String
        
        Private impuestoField As String
        
        Private precioVentaField As String
        
        Private recaudoField As String
        
        Private placaField As String
        
        Private reciboField As String
        
        Private reciboAnuladoField As String
        
        Private onlineField As String
        
        Private codeTarjetaClienteField As String
        
        Private codeTarjetaEmpresaField As String
        
        Private codeValeCreditoField As String
        
        Private codePromocionConsumoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property codeManguera() As String
            Get
                Return Me.codeMangueraField
            End Get
            Set
                Me.codeMangueraField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property codeCara() As String
            Get
                Return Me.codeCaraField
            End Get
            Set
                Me.codeCaraField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property codeSurtidor() As String
            Get
                Return Me.codeSurtidorField
            End Get
            Set
                Me.codeSurtidorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property codeIsla() As String
            Get
                Return Me.codeIslaField
            End Get
            Set
                Me.codeIslaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property codeEstacion() As String
            Get
                Return Me.codeEstacionField
            End Get
            Set
                Me.codeEstacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property serie() As String
            Get
                Return Me.serieField
            End Get
            Set
                Me.serieField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property numero() As String
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property codeSerialImpresora() As String
            Get
                Return Me.codeSerialImpresoraField
            End Get
            Set
                Me.codeSerialImpresoraField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property codeTurnoHorario() As String
            Get
                Return Me.codeTurnoHorarioField
            End Get
            Set
                Me.codeTurnoHorarioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property fechaVenta() As String
            Get
                Return Me.fechaVentaField
            End Get
            Set
                Me.fechaVentaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property fechaProceso() As String
            Get
                Return Me.fechaProcesoField
            End Get
            Set
                Me.fechaProcesoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property fechaApertura() As String
            Get
                Return Me.fechaAperturaField
            End Get
            Set
                Me.fechaAperturaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property fechaLecturaInicio() As String
            Get
                Return Me.fechaLecturaInicioField
            End Get
            Set
                Me.fechaLecturaInicioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property fechaLecturaFin() As String
            Get
                Return Me.fechaLecturaFinField
            End Get
            Set
                Me.fechaLecturaFinField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property lecturaInicio() As String
            Get
                Return Me.lecturaInicioField
            End Get
            Set
                Me.lecturaInicioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property lecturaFinal() As String
            Get
                Return Me.lecturaFinalField
            End Get
            Set
                Me.lecturaFinalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ruc() As String
            Get
                Return Me.rucField
            End Get
            Set
                Me.rucField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property producto() As String
            Get
                Return Me.productoField
            End Get
            Set
                Me.productoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property cantidad() As String
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property precioUnitario() As String
            Get
                Return Me.precioUnitarioField
            End Get
            Set
                Me.precioUnitarioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property valorVenta() As String
            Get
                Return Me.valorVentaField
            End Get
            Set
                Me.valorVentaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property impuesto() As String
            Get
                Return Me.impuestoField
            End Get
            Set
                Me.impuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property precioVenta() As String
            Get
                Return Me.precioVentaField
            End Get
            Set
                Me.precioVentaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property recaudo() As String
            Get
                Return Me.recaudoField
            End Get
            Set
                Me.recaudoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property placa() As String
            Get
                Return Me.placaField
            End Get
            Set
                Me.placaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property recibo() As String
            Get
                Return Me.reciboField
            End Get
            Set
                Me.reciboField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property reciboAnulado() As String
            Get
                Return Me.reciboAnuladoField
            End Get
            Set
                Me.reciboAnuladoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property online() As String
            Get
                Return Me.onlineField
            End Get
            Set
                Me.onlineField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property codeTarjetaCliente() As String
            Get
                Return Me.codeTarjetaClienteField
            End Get
            Set
                Me.codeTarjetaClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property codeTarjetaEmpresa() As String
            Get
                Return Me.codeTarjetaEmpresaField
            End Get
            Set
                Me.codeTarjetaEmpresaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property codeValeCredito() As String
            Get
                Return Me.codeValeCreditoField
            End Get
            Set
                Me.codeValeCreditoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property codePromocionConsumo() As String
            Get
                Return Me.codePromocionConsumoField
            End Get
            Set
                Me.codePromocionConsumoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://pgn.com.pe/pgn-network")>  _
    Partial Public Class RespuestaType
        
        Private esValidaField As String
        
        Private mensajeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property esValida() As String
            Get
                Return Me.esValidaField
            End Get
            Set
                Me.esValidaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://pgn.com.pe/pgn-network")>  _
    Partial Public Class TarjetaType
        
        Private placaField As String
        
        Private codeTarjetaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property placa() As String
            Get
                Return Me.placaField
            End Get
            Set
                Me.placaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property codeTarjeta() As String
            Get
                Return Me.codeTarjetaField
            End Get
            Set
                Me.codeTarjetaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://pgn.com.pe/pgn-network")>  _
    Partial Public Class MensajeType
        
        Private procesoOkField As String
        
        Private mensajeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property procesoOk() As String
            Get
                Return Me.procesoOkField
            End Get
            Set
                Me.procesoOkField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://pgn.com.pe/pgn-network")>  _
    Partial Public Class pgnSolicitudResponse
        
        Private mensajeField As MensajeType
        
        '''<remarks/>
        Public Property mensaje() As MensajeType
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://pgn.com.pe/pgn-network")>  _
    Partial Public Class pgnTarjetaRequest
        
        Private tarjetaField As TarjetaType
        
        '''<remarks/>
        Public Property tarjeta() As TarjetaType
            Get
                Return Me.tarjetaField
            End Get
            Set
                Me.tarjetaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://pgn.com.pe/pgn-network")>  _
    Partial Public Class pgnTarjetaResponse
        
        Private respuestaField As RespuestaType
        
        '''<remarks/>
        Public Property respuesta() As RespuestaType
            Get
                Return Me.respuestaField
            End Get
            Set
                Me.respuestaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub pgnSolicitudCompletedEventHandler(ByVal sender As Object, ByVal e As pgnSolicitudCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class pgnSolicitudCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As pgnSolicitudResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),pgnSolicitudResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub pgnTarjetaCompletedEventHandler(ByVal sender As Object, ByVal e As pgnTarjetaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class pgnTarjetaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As pgnTarjetaResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),pgnTarjetaResponse)
            End Get
        End Property
    End Class
End Namespace
