Imports POSstation.Protocolos
Public Interface iTerminal
    Event AutorizarVentaCheque(Cara As Byte, numeroAutorizacionCheque As String, TipoIdentificacion As Short, kilometraje As String, placa As String, EsVentaCredito As Boolean, puerto As String)
    Event AnularDocumento(Numero As String, idFormaPago As Integer, Documento As String, TipoDocumento As Long, Cara As Byte, Franquicia As String, NroConfirmacion As String, IdTipoDocumento As Long)
    Event AperturaTurno(empleado As String, clave As String, Surtidores As String, puerto As String)
    Event AutorizarVentaManualCredito(Cara As Byte, NumeroAutorizacion As String, puerto As String)
    Event CierreImpresoraPorPuerto(puerto As String)
    Event CierreTurno(empleado As String, clave As String, puerto As String, Surtidores As String)
    Event CierreTurnoTrabajo(empleado As String, ColConsignacion As ColConsignacion, aplicaConsignacion As Boolean, puerto As String)
    Event ConsultarSaldoTarjetaFidelizacion(Tarjeta As String, puerto As String, Ruc As String)
    Event DescuentoClienteRuc(Ruc As String, Cara As String, puerto As String)
    Event EnviarCambioCheque(NumeroAutorizacion As String, idTurno As Long, Cara As Byte, Recibo As String, valorCambio As Double, valorCliente As Double, puerto As String)
    Event EnviarDatosChipMr(Cara As Byte, Datos As String, puerto As String, ByRef Mensaje As String, ByRef EsAutorizado As Boolean)
    Event EnviarRemarcacionCombustible(CodTanqueARemarcar As String, idProductoARemarcar As Byte, Cantidad As Double, CodTanqueNuevo As String, idProductoNuevo As Byte, puerto As String)
    Event EnvioCalibracionCombustible(Cara As Byte, idManguera As Long, idMotivoCalibracion As Integer, aplicaMotivo As Boolean, puerto As String)
    Event EnvioVentaConsumoCombustible(Cara As Byte, puerto As String)
    Event ExcepcionOcurrida(Mensaje As String, Imprime As Boolean, Terminal As Boolean, puerto As String)
    Event FidelizarUltimaVenta(Cara As Byte, cliente As String, IdRedFidelizacion As Integer, puerto As String, Ruc As String)
    Event FidelizarVenta(Cara As Byte, cliente As String, IdRedFidelizacion As Integer, puerto As String, Ruc As String)
    Event GuardarPlaca(cara As Byte, placa As String, esUltimaVenta As Boolean, puerto As String)
    Event ImprimirAjusteTanques(Tanque As String, Producto As String, Cantidad As String, TipoAjuste As Boolean, puerto As String)
    Event ImprimirArqueo(empleado As String, clave As String, puerto As String)
    Event ImprimirArqueoImpresora(puerto As String)
    Event ImprimirDocumentoReciboCombustible(Documento As String, cantidadVenta As Double, puerto As String)
    Event ImprimirFacturaCanastillaUnica(idFactura As String, puerto As String)
    Event ImprimirReciboBypass(Cedula As String, clave As String, tanquePrincipal As String, tanqueHijo As String, puerto As String)
    Event ImprimirResumenDiario(fecha As String, EsMrCombustible As Boolean, puerto As String)
    Event InformarCierreConsignaciones(Cedula As String, clave As String, ColConsignacion As ColConsignacion, aplicaConsignacion As Boolean, puerto As String)
    Event InformarStocksTanquesCierreTurnoServicio(idTurno As Long)
    Event PredeterminarPagoVenta(Cara As Byte, Tarjeta As String, puerto As String)
    Event PrepararTipoDocumento(Cara As Byte, idFormaPago As Integer, TipoDocumento As Long, Documento As String, Franquicia As String, Comprobante As String)
    Event Preset(Cara As Byte, Valor As String, Tipo As Byte, idProducto As Integer, puerto As String)
    Event GuardarKilometraje(Cara As Byte, Kilometraje As String, esUltimaVenta As Boolean, puerto As String)
    Event ReimprimirTurnoPorEmpleado(empleado As String, fecha As String, puerto As String)
    Event ReimprimirTurnoPorSurtidor(Numero As Byte, fecha As String, Surtidor As Byte, puerto As String)
    Event EnviarAlturasCierreDeTanques(Cedula As String, clave As String, AlturasTanques As ColTanques, EsCierrePorAltura As Boolean, puerto As String)
    Event RedencionBonosFidelizacion(NumeroTarjeta As String, Recibo As String, puerto As String)
    Event ReImprimirVentaCreditoPorConsecutivo(Consecutivo As String, puerto As String)
    Event ReimprimirDocumentoPorCara(Cara As Byte, puerto As String)
    Event ReimprimirDocumentoPorNumero(Numero As String, puerto As String)
    Event ReImprimirVentaCreditoPorCara(Cara As Byte)
    Event SolicitudDatosIbutton(Cara As Byte, puerto As String)
    Event VentaCreditoEstacion(cara As Byte, kilometraje As String, puerto As String, identificador As String, IdTipoIdentificacion As Integer, ValorPredeterminado As String)
    Event PagoEnEfectivo(cara As Byte)
    Event ImprimirVentaCanastillaTerpel(recibo As String, puerto As String)
    Event VentaCreditoCanastilla(identificacion As MedioCredito, colProductos As ColCanastilla, Cedula As String, Clave As String, puerto As String)
    Event AnularFacturaCanastilla(prefijo As String, Consecutivo As String, cedulaPrm As String, clavePrm As String, puertoPrm As String)
    Event RegistrarPlaca(cara As Byte, placa As String, esUltimaVenta As Boolean, puerto As String)

End Interface


